###
POST http://localhost:3000/produto/cadastrar
Content-Type: application/json

{
    "nome": "Feijão",
    "codigoBarras": "123456789001",
    "preco": 11,
    "criadoEm": "2021/06/21"
}

###
GET http://localhost:3000/produto/listar